### ISSUE TITLE
How to create plugin chart

### ISSUE THREAD

**Issue by OdysseusC** [tkeel-io/tkeel#7]
# How to create plugin chart

本文档提供了如何构建**tkeel**平台中插件的**chart**包，以便开发的插件能够快速集成到系统中，并能够通过**tkeel-cli**进行安装、卸载等操作。

## Pre-requisites

- [安装Helm](https://helm.sh/)

## Create your plugin chart

1. 初始化一个**chart**
   在你的工作目录下面运行以下命令，初始化一个属于你的**chart**包。
   ```bash
   helm create ${CHART_NAME}
   ```
2. 将对应文件进行修改，并在`${workspace}/${CHART_NAME}/values.yaml`文件头添加以下几行
   ```yaml
   # > tkeel platform values
   # default plugin id
   daprConfig: plugins
   # < tkeel platform values
   ```
3. 修改你的**chart**中的**Deployment**的模板文件，并[注入**dapr**的对应参数](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/#adding-dapr-to-a-kubernetes-deployment)
   类似于：
   ```yaml
   annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nodeapp"
    dapr.io/app-port: "3000"
    dapr.io/config: "tracing"
   ```
4. 将`spec.template.metadata.annotations.dapr.io/config`的值修改为`{{ .Values.daprConfig }}`
   ```yaml
   annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nodeapp"
    dapr.io/app-port: "3000"
    dapr.io/config: {{ .Values.daprConfig }}
   ```

## Package and upload

see [tkeel-io/helm-charts](https://github.com/tkeel-io/helm-charts)
